package com.example.model

enum class AppLanguage(val displayName: String, val code: String) {
  ENGLISH("English", "en"),
  HINDI("हिन्दी (Hindi)", "hi"),
  MARATHI("मराठी (Marathi)", "mr")
}

data class LocalizedStrings(
  val appTitle: String,
  val dashboardTab: String,
  val scraperTab: String,
  val whatsappTab: String,
  val monetizationTab: String,
  val pasteUrlHint: String,
  val analyzeBtn: String,
  val verifiedDeal: String,
  val fakeDiscountAlert: String,
  val priceHistoryTitle: String,
  val currentPriceLabel: String,
  val lowestPriceLabel: String,
  val originalPriceLabel: String,
  val viewChartBtn: String,
  val shareWhatsAppBtn: String,
  val totalSavingsLabel: String,
  val fakeCaughtLabel: String,
  val botStatusOnline: String,
  val botStatusOffline: String,
  val qrPairingTitle: String,
  val qrPairingDesc: String,
  val autoBroadcastLabel: String,
  val affiliateConvertTitle: String,
  val affiliateConvertDesc: String,
  val totalCommissionEarned: String,
  val affiliateClicks: String,
  val conversionRate: String,
  val filterAll: String,
  val filterRealOnly: String,
  val filterFakeOnly: String,
  val filterElectronics: String,
  val filterFashion: String,
  val filterHome: String,
  val fakeReasonPrefix: String,
  val authTab: String,
  val authTitle: String,
  val authSubtitle: String,
  val signInBtn: String,
  val signUpBtn: String,
  val guestSignInBtn: String,
  val signOutBtn: String,
  val emailLabel: String,
  val passwordLabel: String,
  val forgotPasswordBtn: String
)

object Translations {
  val English = LocalizedStrings(
    appTitle = "Shopping AI",
    dashboardTab = "Deals",
    scraperTab = "AI Scraper",
    whatsappTab = "WhatsApp Bot",
    monetizationTab = "Affiliate",
    pasteUrlHint = "Paste Amazon, Flipkart, Myntra product URL...",
    analyzeBtn = "AI Scrape & Verify",
    verifiedDeal = "✅ Verified Real Deal",
    fakeDiscountAlert = "⚠️ Discount Risk Detected",
    priceHistoryTitle = "30-Day Price Trend Analysis",
    currentPriceLabel = "Current Price",
    lowestPriceLabel = "All-Time Low",
    originalPriceLabel = "Stated MRP",
    viewChartBtn = "Price Chart",
    shareWhatsAppBtn = "Send Alert",
    totalSavingsLabel = "Total Tracked Savings",
    fakeCaughtLabel = "Risk Alerts Caught",
    botStatusOnline = "ONLINE (External WhatsApp bridge connected)",
    botStatusOffline = "OFFLINE (Bridge disconnected)",
    qrPairingTitle = "WhatsApp Bridge Authentication",
    qrPairingDesc = "Use a live bridge service to deliver verified WhatsApp alerts and link conversions.",
    autoBroadcastLabel = "Auto-broadcast price drop warnings to subscribers",
    affiliateConvertTitle = "Real-Time Affiliate Link Converter",
    affiliateConvertDesc = "Automatically transforms raw URLs into monetized tracking links with commission tags.",
    totalCommissionEarned = "Estimated Commission",
    affiliateClicks = "Affiliate Clicks",
    conversionRate = "Conversion Rate",
    filterAll = "All Products",
    filterRealOnly = "Verified Deals",
    filterFakeOnly = "Flagged Alerts",
    filterElectronics = "Electronics",
    filterFashion = "Fashion",
    filterHome = "Home & Gadgets",
    fakeReasonPrefix = "AI Verdict:",
    authTab = "Account",
    authTitle = "Firebase Cloud Authentication",
    authSubtitle = "Sign in to sync your tracked products, price drop alerts, and affiliate commission earnings across all your mobile devices.",
    signInBtn = "Sign In",
    signUpBtn = "Create Account",
    guestSignInBtn = "Continue as Guest (Anonymous)",
    signOutBtn = "Sign Out",
    emailLabel = "Email Address",
    passwordLabel = "Password (min 6 chars)",
    forgotPasswordBtn = "Forgot Password?"
  )

  val Hindi = LocalizedStrings(
    appTitle = "शॉपिंग एआई (Shopping AI)",
    dashboardTab = "डील्स",
    scraperTab = "एआई स्क्रैपर",
    whatsappTab = "व्हाट्सएप बॉट",
    monetizationTab = "कमीशन",
    pasteUrlHint = "Amazon, Flipkart या Myntra का यूआरएल पेस्ट करें...",
    analyzeBtn = "एआई विश्लेषण करें",
    verifiedDeal = "✅ असली डिस्काउंट (सत्यापित)",
    fakeDiscountAlert = "⚠️ डिस्काउंट रिस्क चेतावनी",
    priceHistoryTitle = "30 दिनों का मूल्य विश्लेषण",
    currentPriceLabel = "वर्तमान कीमत",
    lowestPriceLabel = "अब तक का न्यूनतम",
    originalPriceLabel = "दर्ज एमआरपी",
    viewChartBtn = "मूल्य चार्ट",
    shareWhatsAppBtn = "अलर्ट भेजें",
    totalSavingsLabel = "कुल बचत",
    fakeCaughtLabel = "जोखिम अलर्ट पकड़े गए",
    botStatusOnline = "सक्रिय (बाह्य व्हॉट्सॲप ब्रिज कनेक्ट आहे)",
    botStatusOffline = "निष्क्रिय (ब्रिज डिस्कनेक्ट आहे)",
    qrPairingTitle = "व्हाट्सॲप ब्रिज प्रमाणीकरण",
    qrPairingDesc = "विश्वसनीय व्हॉट्सॲप अलर्ट वितरीत करण्यासाठी लाइव्ह ब्रिज सोल्यूशन वापरा.",
    autoBroadcastLabel = "सब्सक्राइबर्स को स्वचालित चेतावनी भेजें",
    affiliateConvertTitle = "स्वचालित एफिलिएट लिंक कनवर्टर",
    affiliateConvertDesc = "सामान्य लिंक्स को स्वतः मुद्रीकृत एफिलिएट ट्रैकिंग लिंक्स में बदलता है।",
    totalCommissionEarned = "अनुमानित कमीशन कमाई",
    affiliateClicks = "एफिलिएट क्लिक्स",
    conversionRate = "कन्वर्ज़न दर",
    filterAll = "सभी उत्पाद",
    filterRealOnly = "असली डील्स",
    filterFakeOnly = "संभावित अलर्ट",
    filterElectronics = "इलेक्ट्रॉनिक्स",
    filterFashion = "फैशन",
    filterHome = "होम व गैजेट्स",
    fakeReasonPrefix = "एआई जांच:",
    authTab = "खाता",
    authTitle = "फायरबेस क्लाउड प्रमाणीकरण",
    authSubtitle = "अपने ट्रैक किए गए उत्पादों, मूल्य अलर्ट और एफिलिएट कमाई को सभी उपकरणों में सिंक करने के लिए साइन इन करें।",
    signInBtn = "लॉग इन करें",
    signUpBtn = "नया खाता बनाएं",
    guestSignInBtn = "अतिथि के रूप में जारी रखें (Guest)",
    signOutBtn = "लॉग आउट करें",
    emailLabel = "ईमेल पता",
    passwordLabel = "पासवर्ड (कम से कम 6 अक्षर)",
    forgotPasswordBtn = "पासवर्ड भूल गए?"
  )

  val Marathi = LocalizedStrings(
    appTitle = "शॉपिंग एआय (Shopping AI)",
    dashboardTab = "डील्स",
    scraperTab = "एआय स्क्रॅपर",
    whatsappTab = "व्हॉट्सॲप बॉट",
    monetizationTab = "कमिशन",
    pasteUrlHint = "Amazon, Flipkart किंवा Myntra लिंक पेस्ट करा...",
    analyzeBtn = "एआय विश्लेषण करा",
    verifiedDeal = "✅ खरी सवलत (प्रमाणित)",
    fakeDiscountAlert = "⚠️ सूट जोखीम ओळखली",
    priceHistoryTitle = "30 दिवसांचा किंमत इतिहास",
    currentPriceLabel = "सध्याची किंमत",
    lowestPriceLabel = "आत्तापर्यंतची सर्वात कमी",
    originalPriceLabel = "मूळ एमआरपी",
    viewChartBtn = "किंमत आलेख",
    shareWhatsAppBtn = "अलर्ट पाठवा",
    totalSavingsLabel = "एकूण बचत",
    fakeCaughtLabel = "जोखिम अलर्ट पकडले",
    botStatusOnline = "सक्रिय (व्हॉट्सॲप ब्रिज सर्व्हिस कनेक्ट केली आहे)",
    botStatusOffline = "बंद (ब्रिज कनेक्शन उपलब्ध नाही)",
    qrPairingTitle = "व्हॉट्सॲप ब्रिज प्रमाणीकरण",
    qrPairingDesc = "तुमच्या ब्रिज सोल्यूशनशी कनेक्ट करण्यासाठी QR स्कॅन करा आणि थेट अलर्ट वितरीत करण्यासाठी तयार व्हा.",
    autoBroadcastLabel = "ग्राहकांना स्वयंचलित चेतावणी संदेश पाठवा",
    affiliateConvertTitle = "रिअल-टाईम अफिलिएट लिंक कनवर्टर",
    affiliateConvertDesc = "सामान्य लिंक्सना कमिशन टॅगसह कमाईच्या लिंक्समध्ये आपोआप रूपांतरित करते.",
    totalCommissionEarned = "अंदाजित कमिशन कमाई",
    affiliateClicks = "अफिलिएट क्लिक्स",
    conversionRate = "कन्वर्शन दर",
    filterAll = "सर्व उत्पादने",
    filterRealOnly = "खऱ्या डील्स",
    filterFakeOnly = "संभाव्य अलर्ट",
    filterElectronics = "इलेक्ट्रॉनिक्स",
    filterFashion = "फॅशन",
    filterHome = "होम आणि गॅजेट्स",
    fakeReasonPrefix = "एआय तपासणी:",
    authTab = "खाते",
    authTitle = "फायरबेस क्लाउड प्रमाणीकरण",
    authSubtitle = "तुमची ट्रॅक केलेली उत्पादने, किंमत अलर्ट आणि कमिशन कमाई सर्व उपकरणांवर सिंक करण्यासाठी साइन इन करा.",
    signInBtn = "लॉग इन करा",
    signUpBtn = "नवीन खाते तयार करा",
    guestSignInBtn = "पाहुणे म्हणून सुरू ठेवा (Guest)",
    signOutBtn = "लॉग आऊट करा",
    emailLabel = "ईमेल पत्ता",
    passwordLabel = "पासवर्ड (किमान 6 अक्षरे)",
    forgotPasswordBtn = "पासवर्ड विसरलात?"
  )

  fun get(lang: AppLanguage): LocalizedStrings = when (lang) {
    AppLanguage.ENGLISH -> English
    AppLanguage.HINDI -> Hindi
    AppLanguage.MARATHI -> Marathi
  }
}
